name: .NET CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # Change '7.0' to '8.0'
    - name: Restore dependencies
      run: dotnet Restore
    - name: Build the application
      run: dotnet build --configuration Release #removed no-restore
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

# this isn't working